version: "3.7"

services:

  webapp:
    build:
      context: api
    depends_on:
      - backend
    environment:
      - JENA_HOST=tmrweb_fuseki_1
      - PROLOG_HOST=tmrweb_backend_1
    restart: unless-stopped

  backend:
    build:
      context: backend
    depends_on:
      - fuseki
    environment:
      - FUSEKI_HOST_PORT=http://tmrweb_fuseki_1:3030/
    restart: unless-stopped

  fuseki:
    build:
      context: fuseki
    volumes:
      - drug_volume:/fuskei
    environment:
      - ADMIN_PASSWORD=Izf3TaF0UI8oj7f
    restart: unless-stopped

volumes:
  drug_volume:

networks:
  default:
    external:
      name: hi_default
