version: "3.7"

services:

  proxy:
    build:
      context: proxy
    depends_on:
      - webapp
    command: ["./wait-for-it.sh", "--timeout=0", "tmrweb_webapp_1:8888", "--", "nginx", "-g", "daemon off;"]
    tty: true
    ports:
      - '443:443'
      - '80:80'
    restart: unless-stopped

  webapp:
    build:
      context: api
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: backend
    environment:
      - FUSEKI_HOST_PORT=http://tmrweb_fuseki_1:3030/
    depends_on:
      - fuseki
    restart: unless-stopped

  fuseki:
    build:
      context: fuseki
    volumes:
      - drug_volume:/fuskei
    environment:
      - ADMIN_PASSWORD=Izf3TaF0UI8oj7f
    restart: unless-stopped

volumes:
  drug_volume:
